# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eed30a7d03c4a40ad6f638c829eb9309b805d99f7bede9ede5e89dbbc2ee324be2c5c9a8538053813b61a79d47f332d09d75235d23c14e8a88651bf7bf398c8

test:
  secret_key_base: ea437df72cb96037f4128cc43a70973f6c296dfc759d4755fa3385e7bd70b19851d4095a11587d76ab111683fabb3a087585cb209965a0cf536a5c43755f3819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
